// 2001.05.25
#ifndef __KZP_H__
#define __KZP_H__

#define WC_KZP  "kzpClass"
#define ID_KZP  1

#define IDB_HANENG      100
#define IDB_IM          101
//#define IDB_KZP         102

#define ID_POPUP        100
#define IDM_HIDE        101
#define IDM_OPTIONS     102
#define IDM_EXIT        103

#define KZPM_CHANGEHAN      ( WM_USER + 1 )
#define KZPM_SETHAN         ( WM_USER + 2 )
#define KZPM_QUERYHAN       ( WM_USER + 3 )

#define KZPM_CHANGEIM       ( WM_USER + 4 )
#define KZPM_SETIM          ( WM_USER + 5 )
#define KZPM_QUERYIM        ( WM_USER + 6 )

#endif
